### ISSUE TITLE
chat doesnt auto scroll

### ISSUE THREAD

**Issue by smelvinjones** [z3db0y/rays-nova#2]
the chat doesnt auto scroll and when you enter the next game (like in same lobby) it stops updating until u refresh

**Comment by z3db0y** [comment]
So the issue is the scrolling itself; no issues with new messages not being added? Because I have noticed the scrolling issue as well and will fix it in the near future

**Comment by smelvinjones** [comment]
> and when you enter the next game (like in same lobby) it stops updating until u refresh

edit: when there are more than 34 or 35 lines in the chat (whether its killfeed or chat or whatever and doesnt matter if it is hidden/not selected) then it stops updating

**Comment by z3db0y** [comment]
o shi i forgor abt this issue
will fix rq

**Comment by z3db0y** [comment]
Fixed in 0b45cf9cb39a43a3f7223c4200a2739cc7999cc9
