### ISSUE TITLE
wont launch

### ISSUE THREAD

**Issue by smelvinjones** [z3db0y/rays-nova#3]
client wont launch and gives this error in the picture
![Capture](https://github.com/z3db0y/rays-nova/assets/163516393/38f9bfad-2db7-4925-afa4-ad486176a65a)

reinstall didnt help

specs: 
windows 10 home
ryzen 7 5800x 
rtx 3060

**Comment by z3db0y** [comment]
Alright, I'll patch when I get home, thanks.

**Comment by z3db0y** [comment]
update: should be good now lmk if issue still persists
8c86f9ca3344245e8feeb74784353808650cf218
